Revert "Powerhub: Bring back UDFPS Icons & Animations [2/3]"
This reverts commit de54c8f362d94bccd50da4c1104dbdf694075574.

packages/apps/Settings/Powerhub/src/com/power/hub/fragments/lockscreen/UdfpsAnimation.java:137: error: cannot find symbol
            Glide.with(holder.image.getContext())
            ^
  symbol:   variable Glide
  location: class UdfpsAnimation.UdfpsAnimAdapter
packages/apps/Settings/Powerhub/src/com/power/hub/fragments/lockscreen/UdfpsIconPicker.java:149: error: cannot find symbol
            Glide.with(holder.image.getContext())
            ^
  symbol:   variable Glide
  location: class UdfpsIconPicker.UdfpsIconAdapter
4 errors